[package]
name = "deltav_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = { workspace = true }
polars.workspace = true
reqwest = { workspace = true, features = ["stream"] }
thiserror = { workspace = true }
tokio = { workspace = true }
url.workspace = true
