[package]
name = "deltav_core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
deltav_utils = { path = "../utils" }
reqwest = { workspace = true, features = ["stream"] }
futures-util = { workspace = true }
tokio.workspace = true
